# Generated by Django 5.2.5 on 2025-08-25 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_reaction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
